# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- '*'

pool:
  name: 'BA_Pool'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NEt SDK 6.x'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: Npm@1
  inputs:
    command: 'install'

- task: CmdLine@2
  inputs:
    script: 'C:\Users\Brian\AppData\Roaming\npm\node-sass.cmd Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'

- task: gulp@0
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 
    gulpjs: 'node_modules/gulp/bin/gulp.js'
    enableCodeCoverage: false
  
- task: CmdLine@2
  inputs:
    script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    workingDirectory: 'Tailspin.SpaceGame.Web/wwwroot'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--no-restore --configuration Release'