trigger:
- main

pool:
    name: BA_Pool

variables:
    buildConfiguration: 'Release'

steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'